---
title: "DRAFT `r params$year` Risk Policy Report for `r params$stock`"
date: "`r params$draft_date`"
output: pdf_document
params: # NA because they will be replaced by the shiny app parameters
    year: NA
    stock: NA 
    fmp: NA 
    draft_date: NA
    # matrix_tbl: NA
    scores: NA
    plot_data: NA
    zscore: NA
    RecProb: NA
    # plot: NA
    tier: NA
    # rationale: NA
---
```{r setup, include=FALSE}
# set echo in all code chunks so they are not included in the output file
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
library(gt)
library(tidyverse)
# library(flextable)
library(kableExtra)
library(here)
source(here("helpers.R"))
```


<!-- ```{r matrix-ft}
# set_flextable_defaults(na_str = "")

# params$matrix_tbl |> 
#     mutate(answer = case_when(
#         is.na(answer) ~ "Not Provided", 
#         TRUE ~ answer
#     )) |> 
#     flextable() |> 
#     merge_v(j = "factor") |> 
#     set_header_labels(facor = "Factor", 
#                       value = "Value", 
#                       answer = "Supporting Information") |> 
#     border_inner() |> 
#     width(width = c(1.5, 2.0, 3.5)) |> 
#     align(j = 3, align = "justify")
``` -->

<!-- ```{r matrix-kbl}
# params$matrix_tbl |> 
#     rename_all(str_to_title) |> 
#     rename(#" " = "factor", 
#     #     " " = "value",
#         "Supporting Information" = "Answer") |> 
#     knitr::kable(booktabs = T) |> #, col.names = NULL) |> 
#     # add_header_above(c(" " = 1, "Supporting Information" = 2)) |>
#     kable_styling(latex_options = c("hold_position", "scale_down"), position = "float_left", fixed_thead = T) |>
#     column_spec(column = 1:2, width = "3cm") |> 
#     collapse_rows(columns = 1, valign = "top", latex_hline = "full", longtable_clean_cut = F) |> 
#     # pack_rows("Stock status and Uncertainty", 1, 19, latex_align = "c") |>
#     column_spec(column = 3, width = "10cm")

``` -->

<!-- \newpage  -->

## Scores and Weights 

```{r scores}

params$scores |> tab_options(table.width = pct(100), latex.tbl.pos = "ht") 

```

The calculated z-score is **`r params$zscore`**. The recommended probability is **`r params$RecProb`**.\  


## Recommended Probability
The level of risk that should be considered based on the z-score and recommended probability for `r params$stock` is _`r params$tier`._\
\

```{r zplot, fig.height = 4.5}
plotRecProb(data = params$plot_data, 
              z = zscore, 
              RecProb = RecProb, 
              size = 2.5) + 
    ggplot2::theme(legend.text = element_text(size = 8))
```


